---@diagnostic disable: newfield-call
Config = Config or {}

Config.Debug = false -- Set to True to enable Debug Prints
Config.MoneyType = 'bank'
Config.RepairMoneyType = 'cash'
Config.allowGovPlateIndex = false -- Setting this to true will allow all vehicles to purchase gov plate index "Sinine on Valge #3" (only for emergency vehicles otherwise)
maxVehiclePerformanceUpgrades = 0 -- | All Upgrades: 0 | No Upgrades: -1 | Can be -1 to 4

-- ADJUST PRICING
vehicleCustomisationPrices = {
    cosmetics = {price = 400},
    respray = {price = 300},
    performance = {prices = {0, 3250, 5500, 10450, 15250, 20500, 25000}},
    turbo = {prices = {0, 15000}},
    wheels = {price = 400},
    customwheels = {price = 600},
    wheelsmoke = {price = 400},
    windowtint = {price = 400},
    neonside = {price = 100},
    neoncolours = {price = 500},
    headlights = {price = 100},
    xenoncolours = {price = 500},
    oldlivery = {price = 500},
    plateindex = {price = 500}
}

-- WINDOW TINTS

vehicleWindowTintOptions = {
    {name = "0%", id = 0},
    {name = "25%", id = 1},
    {name = "50%", id = 2},
    {name = "95%", id = 3}
}

-- HEADHeleS

vehicleXenonOptions = {
    xenonColours = {
        {name = "Tuunimata", id = 255},
        {name = "Valge", id = 0}, {name = "Sinine", id = 1},
        {name = "Elektrisinine", id = 2},
        {name = "Mündiroheline", id = 3},
        {name = "Laimioheline", id = 4},
        {name = "Kollane", id = 5},
        {name = "Kuldne", id = 6},
        {name = "Oranz", id = 7},
        {name = "Punane", id = 8},
        {name = "Pony Roosa", id = 9},
        {name = "Kuum Roosa", id = 10},
        {name = "Lilla", id = 11},
        {name = "Tumesinine", id = 12}
    }
}

-- WHEELS

vehicleWheelOptions = {
    {category = "Custom", id = -1, wheelID = 23},
    {category = "Rehvisuits", id = 20, wheelID = 23},
    {category = "Sport", id = 0, wheelID = 23},
    {category = "Muskli", id = 1, wheelID = 23},
    {category = "Lowrider", id = 2, wheelID = 23},
    {category = "SUV", id = 3, wheelID = 23},
    {category = "Maastik", id = 4, wheelID = 23},
    {category = "Tuner", id = 5, wheelID = 23},
    {category = "Mootorratta", id = 6, wheelID = 23},
    {category = "Kõrgklass", id = 7, wheelID = 23},
    {category = "Bennys", id = 8, wheelID = 23},
    {category = "Erilised", id = 9, wheelID = 23},
    {category = "Drag", id = 10, wheelID = 23},
    {category = "Tänava", id = 11, wheelID = 23},
    {category = "Ralli", id = 12, wheelID = 23},
}

-- TIRE Suits

vehicleTyreSmokeOptions = {
    { name = "Valge Suits", r = 254, g = 254, b = 254},
    { name = "Must Suits", r = 1, g = 1, b = 1},
    { name = "Sinine Suits", r = 0, g = 150, b = 255},
    { name = "Kollane Suits", r = 255, g = 255, b = 50},
    { name = "Oranz Suits", r = 255, g = 153, b = 51},
    { name = "Punane Suits", r = 255, g = 10, b = 10},
    { name = "Roheline Suits", r = 10, g = 255, b = 10},
    { name = "Lilla Suits", r = 153, g = 10, b = 153},
    { name = "Roosa Suits", r = 255, g = 102, b = 178},
    { name = "Gray Suits", r = 128, g = 128, b = 128}
}

-- NEONS

vehicleNeonOptions = {
    category = "Neons",
    neonTypes = {
        {name = "Eesmised Põhjatuled", id = 2},
        {name = "Tagumised Põhjatuled", id = 3},
        {name = "Vasakpoolsed Põhjatuled", id = 0},
        {name = "Parempoolsed Põhjatuled", id = 1}
    },
    neonColours = {
        { name = "Valge", r = 222, g = 222, b = 255},
        { name = "Sinine", r = 2, g = 21, b = 255},
        { name = "Elektrisinine", r = 3, g = 83, b = 255},
        { name = "Mündiroheline", r = 0, g = 255, b = 140},
        { name = "Laimiroheline", r = 94, g = 255, b = 1},
        { name = "Kollane", r = 255, g = 255, b = 0},
        { name = "Kuldne", r = 255, g = 150, b = 0},
        { name = "Oranz", r = 255, g = 62, b = 0},
        { name = "Punane", r = 255, g = 1, b = 1},
        { name = "Pony Roosa", r = 255, g = 50, b = 100},
        { name = "Kuum Roosa", r = 255, g = 5, b = 190},
        { name = "Lilla", r = 35, g = 1, b = 255},
        { name = "Tumesinine", r = 15, g = 3, b = 255}
    }
}

-- MAIN COMPONENTS

vehicleCustomisation = {
    {category = "Spoiler", id = 0},
    {category = "Esistange", id = 1},
    {category = "Tagastange", id = 2},
    {category = "Küljekarp", id = 3},
    {category = "Summuti", id = 4},
    {category = "Kaitseraam", id = 5},
    {category = "Iluvõre", id = 6},
    {category = "kapott", id = 7},
    {category = "Vasakpoolne poritiib", id = 8},
    {category = "Parempoolne poritiib", id = 9},
    {category = "Katus", id = 10},
    {category = "Mootor", id = 11},
    {category = "Pidurid", id = 12},
    {category = "Käigukast", id = 13},
    {category = "Vedrustus", id = 15},
    {category = "Armor", id = 16},
    {category = "Turbo", id = 18},
    {category = "Numbrimärk", id = 25},
    {category = "Trim A", id = 27},
    {category = "Trim B", id = 44},
    {category = "Kaunistused", id = 28},
    {category = "Armatuurlaud", id = 29},
    {category = "Mõõdikud", id = 30},
    {category = "Uksekõlar", id = 31},
    {category = "Istmed", id = 32},
    {category = "Rool", id = 33},
    {category = "Käiguhoob", id = 34},
    {category = "Katt", id = 35},
    {category = "Kõlar", id = 36},
    {category = "Pagasiruum", id = 37},
    {category = "Hüdrauulika", id = 38},
    {category = "Mootoriplokk", id = 39},
    {category = "Õhufilter", id = 40},
    {category = "Amordid", id = 41},
    {category = "Tiivakate", id = 42},
    {category = "Antenn", id = 43},
    {category = "Kütusepaak", id = 45},
    {category = "Aken", id = 46},
    {category = "Kleebised", id = 48},
    {category = "Signaal", id = 14,
        PiipNames = {
            {name = "Rekka Signaal", id = 0},
            {name = "Cop Signaal", id = 1},
            {name = "Clown Signaal", id = 2},
            {name = "Musikaalne Signaal 1", id = 3},
            {name = "Musikaalne Signaal 2", id = 4},
            {name = "Musikaalne Signaal 3", id = 5},
            {name = "Musikaalne Signaal 4", id = 6},
            {name = "Musikaalne Signaal 5", id = 7},
            {name = "Kurb Tromboon", id = 8},
            {name = "Klassikaline Signaal 1", id = 9},
            {name = "Klassikaline Signaal 2", id = 10},
            {name = "Klassikaline Signaal 3", id = 11},
            {name = "Klassikaline Signaal 4", id = 12},
            {name = "Klassikaline Signaal 5", id = 13},
            {name = "Klassikaline Signaal 6", id = 14},
            {name = "Klassikaline Signaal 7", id = 15},
            {name = "Skaala - Do", id = 16},
            {name = "Skaala - Re", id = 17},
            {name = "Skaala - Mi", id = 18},
            {name = "Skaala - Fa", id = 19},
            {name = "Skaala - Sol", id = 20},
            {name = "Skaala - La", id = 21},
            {name = "Skaala - Ti", id = 22},
            {name = "Skaala - Do", id = 23},
            {name = "Jazz Signaal 1", id = 24},
            {name = "Jazz Signaal 2", id = 25},
            {name = "Jazz Signaal 3", id = 26},
            {name = "Jazz Signaal Korduv", id = 27},
            {name = "Tärniga sädelev bänner 1", id = 28},
            {name = "Tärniga sädelev bänner 2", id = 29},
            {name = "Tärniga sädelev bänner 3", id = 30},
            {name = "Tärniga sädelev bänner 4", id = 31},
            {name = "Klassikaline Signaal 8 Korduv", id = 32},
            {name = "Klassikaline Signaal 9 Korduv", id = 33},
            {name = "Klassikaline Signaal 10 Korduv", id = 34},
            {name = "Klassikaline Signaal 8", id = 35},
            {name = "Klassikaline Signaal 9", id = 36},
            {name = "Klassikaline Signaal 10", id = 37},
            {name = "Matused Korduv", id = 38},
            {name = "Matused", id = 39},
            {name = "Hirmus Korduv", id = 40},
            {name = "Hirmus", id = 41},
            {name = "San Andreas Korduv", id = 42},
            {name = "San Andreas", id = 43},
            {name = "Liberty City Korduv", id = 44},
            {name = "Liberty City", id = 45},
            {name = "Jõululik 1 Korduv", id = 46},
            {name = "Jõululik 1", id = 47},
            {name = "Jõululik 2 Korduv", id = 48},
            {name = "Jõululik 2", id = 49},
            {name = "Jõululik 3 Korduv", id = 50},
            {name = "Jõululik 3", id = 51}
        }
    }
}

-- COLORS

vehicleResprayOptions = {
    {category = "Classic", id = 0,
        colours = {
            {name = "Must", id = 0},
            {name = "Jäävalge", id = 111},
            {name = "Lumivalge", id = 112},
            {name = "Süsinik Must", id = 147},
            {name = "Grafiit", id = 1},
            {name = "Antratsiit Must", id = 11},
            {name = "Must Teras", id = 11},
            {name = "Tume Teras", id = 3},
            {name = "Hõbedane", id = 4},
            {name = "Sinakas Hõbedane", id = 5},
            {name = "Rullitud Teras", id = 6},
            {name = "Varju Hõbedane", id = 7},
            {name = "Kivi Hõbedane", id = 8},
            {name = "Kesköö Hõbedane", id = 9},
            {name = "Malm Hõbedane", id = 10},
            {name = "Punane", id = 27},
            {name = "Torino Punane", id = 28},
            {name = "Vormeli Punane", id = 29},
            {name = "Laavapunane", id = 150},
            {name = "Leekpunane", id = 30},
            {name = "Graatsia Punane", id = 31},
            {name = "Granaat Punane", id = 32},
            {name = "Päikeseloojangu Punane", id = 33},
            {name = "Viinamarja Punane", id = 34},
            {name = "Veini Punane", id = 143},
            {name = "Kommi Punane", id = 35},
            {name = "Kuum Roosa", id = 135},
            {name = "Pfsiter Roosa", id = 137},
            {name = "Lõheroosa", id = 136},
            {name = "Päikeseloojangu Oranz", id = 36},
            {name = "Oranz", id = 38},
            {name = "Heleoranz", id = 138},
            {name = "Kuld", id = 99},
            {name = "Pronks", id = 90},
            {name = "Kollane", id = 88},
            {name = "Rallikollane", id = 89},
            {name = "Kastekollane", id = 91},
            {name = "Tumeroheline", id = 49},
            {name = "Ralliroheline", id = 50},
            {name = "Mereroheline", id = 51},
            {name = "Oliiviroheline", id = 52},
            {name = "Heleroheline", id = 53},
            {name = "Bensiini Roheline", id = 54},
            {name = "Laimiroheline", id = 92},
            {name = "Kesköö Sinine", id = 141},
            {name = "Galaktika Sinine", id = 61},
            {name = "Tumesinine", id = 62},
            {name = "Saxon Sinine", id = 63},
            {name = "Sinine", id = 64},
            {name = "Meresinine", id = 65},
            {name = "Sadamasinine", id = 66},
            {name = "Teemantsinine", id = 67},
            {name = "Surfi Sinine", id = 68},
            {name = "Merendus Sinine", id = 69},
            {name = "Rallisinine", id = 73},
            {name = "Ultra Sinine", id = 70},
            {name = "Helesinine", id = 74},
            {name = "Šhokolaadipruun", id = 96},
            {name = "Piisoni pruun", id = 101},
            {name = "Pähkli Pruun", id = 95},
            {name = "Feltzer Pruun", id = 94},
            {name = "Vahtra Pruun", id = 97},
            {name = "Pöögipuu Pruun", id = 103},
            {name = "Sienna Pruun", id = 104},
            {name = "Sadula Pruun", id = 98},
            {name = "Sambla Pruun", id = 100},
            {name = "Pöögi Pruun", id = 102},
            {name = "Õlekõrre Pruun", id = 99},
            {name = "Sandy Pruun", id = 105},
            {name = "Pleegitatud Pruun", id = 106},
            {name = "Schafter Lilla", id = 71},
            {name = "Spinnaker Lilla", id = 72},
            {name = "Kesköö Lilla", id = 142},
            {name = "Helelilla", id = 145},
            {name = "Kreemjas", id = 107}
        }
    },
    {category = "Metallic", id = 1,
        colours = {{name = "Must", id = 0},
            {name = "Karbon Must", id = 147},
            {name = "Grafiit", id = 1},
            {name = "Antrasiit Must", id = 11},
            {name = "Must Teras", id = 11},
            {name = "Tume Teras", id = 3},
            {name = "Hõbedane", id = 4},
            {name = "Sinakas Hõbedane", id = 5},
            {name = "Valtsitud Teras", id = 6},
            {name = "Varju Hõbedane", id = 7},
            {name = "Kivi Hõbedane", id = 8},
            {name = "Kesköö Hõbedane", id = 9},
            {name = "Panni Hõbedane", id = 10},
            {name = "Punane", id = 27},
            {name = "Torino Punane", id = 28},
            {name = "Formula Punane", id = 29},
            {name = "Laavaunane", id = 150},
            {name = "Leekpunane", id = 30},
            {name = "Graatsia Punane", id = 31},
            {name = "Granaat Punane", id = 32},
            {name = "Päikeseloojangu unane", id = 33},
            {name = "Viinamarja Punane", id = 34},
            {name = "Veini Punane", id = 143},
            {name = "Kommi Punane", id = 35},
            {name = "Kuum Roosa", id = 135},
            {name = "Pfsiter Roosa", id = 137},
            {name = "Lõheroosa", id = 136},
            {name = "Päikeseloojangu Oranz", id = 36},
            {name = "Oranz", id = 38},
            {name = "Heleoranz", id = 138},
            {name = "Kuld", id = 99},
            {name = "Pronks", id = 90},
            {name = "Kollane", id = 88},
            {name = "Rallikollane", id = 89},
            {name = "Kastekollane", id = 91},
            {name = "Tumeroheline", id = 49},
            {name = "Ralliroheline", id = 50},
            {name = "Mereroheline", id = 51},
            {name = "Oliiviroheline", id = 52},
            {name = "Heleroheline", id = 53},
            {name = "Bensiini Roheline", id = 54},
            {name = "Laimiroheline", id = 92},
            {name = "Kesköö Sinine", id = 141},
            {name = "Galaktika Sinine", id = 61},
            {name = "Tumesinine", id = 62},
            {name = "Saxon Sinine", id = 63},
            {name = "Sinine", id = 64},
            {name = "Meresinine", id = 65},
            {name = "Sadamasinine", id = 66},
            {name = "Teemantsinine", id = 67},
            {name = "Surfi Sinine", id = 68},
            {name = "Merendus Sinine", id = 69},
            {name = "Rallisinine", id = 73},
            {name = "Ultra Sinine", id = 70},
            {name = "Helesinine", id = 74},
            {name = "Šhokolaadipruun", id = 96},
            {name = "Piisoni Pruun", id = 101},
            {name = "Pähkli Pruun", id = 95},
            {name = "Feltzer Pruun", id = 94},
            {name = "Vahtra Pruun", id = 97},
            {name = "Pöögipuu Pruun", id = 103},
            {name = "Sienna Pruun", id = 104},
            {name = "Sadula Pruun", id = 98},
            {name = "Sambla Pruun", id = 100},
            {name = "Pöögi Pruun", id = 102},
            {name = "Õlekõrre Pruun", id = 99},
            {name = "Sandy Pruun", id = 105},
            {name = "Pleegitatud Pruun", id = 106},
            {name = "Schafter Lilla", id = 71},
            {name = "Spinnaker Lilla", id = 72},
            {name = "Kesköö Lilla", id = 142},
            {name = "Helelilla", id = 145},
            {name = "Kreemjas", id = 107},
            {name = "Jäävalge", id = 111},
            {name = "Lumivalge", id = 112}
        }
    },
    {category = "Matt", id = 2,
        colours = {{name = "Must", id = 12},
            {name = "Hall", id = 13},
            {name = "Helehall", id = 14},
            {name = "Jäävalge", id = 131},
            {name = "Sinine", id = 83},
            {name = "Tumesinine", id = 82},
            {name = "kesköö Sinine", id = 84},
            {name = "Kesköö Lilla", id = 149},
            {name = "Schafter Lilla", id = 148},
            {name = "Punane", id = 39},
            {name = "Tumepunane", id = 40},
            {name = "Oranz", id = 41},
            {name = "Kollane", id = 42},
            {name = "Laimiroheline", id = 55},
            {name = "Roheline", id = 128},
            {name = "Metsaroheline", id = 151},
            {name = "Leheroheline", id = 155},
            {name = "Oliiviroheline ", id = 152},
            {name = "Tumepruun", id = 153},
            {name = "Kõrbepruun", id = 154}
        }
    },
    {category = "Metals", id = 3,
            colours = {{name = "Poleeritud Teras", id = 117},
            {name = "Poleeritud Must Teras", id = 118},
            {name = "Poleeritud Aluminium", id = 119},
            {name = "Puhas Kuld", id = 158},
            {name = "Poleeritud Kuld", id = 159},
            {name = "Kroom", id = 120}
        }
    }
}
